### ISSUE TITLE
Not installing on L4T 36.3.0 jetson AGX Orin 64 Dev-kit

### ISSUE THREAD

**Issue by salvadorscardua** [Seeed-Projects/jetson-examples#17] opened 2024-08-23 00:42 UTC
Error running:
$ reComputer run ultralytics-yolo

![err](https://github.com/user-attachments/assets/ce225392-9f9f-4d77-a860-f518c08c49c7)

**Comment by yuyoujiang** [comment] 2024-08-23 10:32
Thank you @salvadorscardua !  The issue was caused by two factors:
1. `yq` was not installed correctly.
2. There was an error in the configuration file path.

This issue has been fixed in version `0.1.7`. You can reinstall `jetson-example` and try running `ultralytics-yolo` again.

**Comment by smbunn** [comment] 2024-08-29 02:26
I have had exactly the same issue today with a Jetson Orin Nano.  I downloaded the latest jetson-example (today) and still got the error message that LT36.3.0 is not allowed.  I then separately installed yq using:

```
sudo add-apt-repository ppa:rmescandon/yq
sudo apt update
sudo apt install yq -y
```

and then re-ran  ```reComputer run ultralytics-yolo``` and after a very long time with endless install messages ...  it failed again with exactly the same error message
```
Processing triggers for ghc (8.8.4-3) ...
L4T VERSION 36.3.0 is not in the allowed versions list.
An error occurred. Exiting...
```

I then tried any of the other examples, (I tried ```reComputer run yolov10 ```) and they all give the same error message 

```36.3.0
L4T_VERSION: 36.3.0
L4T_VERSION is not in the allowed versions list. Exiting.
```
Just tried llama3 and that one worked OK

yolov8-rail-inspection had a differnet failure

```
INFO: machine[nvidia jetson orin nano developer kit] confirmed...
run example：yolov8-rail-inspection
WARN: Example[yolov8-rail-inspection] init.sh Not Found.
----example start----
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.47/images/create?fromImage=yaohui1998%2Fbolt_inspection&tag=1.0": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.47/containers/json?all=1&filters=%7B%22name%22%3A%7B%22yolov8_rain_inspection%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by yuyoujiang** [comment] 2024-08-29 11:37
The program failed to start due to incorrect Jetson device resource detection. I will quickly fix these issues and provide feedback.

**Comment by yuyoujiang** [comment] 2024-08-30 11:40
Thank you @smbunn  !!! Some containers have been found to be unable to run on JetPack 6.0. We will test and fix them gradually. `ultralytics-yolo`, `yolov10`, `yolov8-rail-inspection`  have already been updated.

**Comment by salvadorscardua** [comment] 2024-08-30 16:22
i tested again on my AGX ORIN Dev-kit with jetpack 6.0 and **ultralytics-yolo** works properly! 

Thank you! amazing tool and support!

**Comment by smbunn** [comment] 2024-08-31 00:06
Just tried yolov10 again, same error.  I completely unistalled jetson-examples.  deleted the folders from my home dircetory, rebooted and re-installed.  llava is working.  It used to run a whole heap of commands downloading containers etc, now it fails instantly in 3 lines:

```
simon@Jetson-Orin:~$ reComputer run yolov10
INFO: machine[nvidia jetson orin nano developer kit] confirmed...
run example：yolov10
----example init----
36.3.0
L4T_VERSION: 36.3.0
L4T_VERSION is not in the allowed versions list. Exiting.
An error occurred. Exiting...
simon@Jetson-Orin:~$
```

same with ultralytics-yolo

**Comment by almarion** [comment] 2024-08-31 03:26
Just to confirm that attempts to run jetson-examples on Orin Nano Jetpack 6  gives: 
    L4T_VERSION: 36.3.0
    L4T_VERSION is not in the allowed versions list. Exiting.
for yolo and other examples ...
I am using the non-docker approach
Installation via PyPI (Recommended)

**Comment by yuyoujiang** [comment] 2024-08-31 16:11
Please update his version to 0.1.8 by ` pip install --upgrade jetson-examples`

**Comment by almarion** [comment] 2024-09-01 00:10
Hi yuyoujiang,
First thanks for replying so quickly to my comment.
After making sure I was using jet-examples version 0.1.8,  I ran "reComputer run ultralytics-yolo".
It turns out that all script files (including run.sh) have the Windows/DOS format (i.e. CRLF) and NOT the Linux format (LF) for line termination.  So I had to convert them.  After that at least the install could continue.  At some point, all activity seemed be complete, but no indication of success.  Not sure if did a reboot and/or issued the reComputer command, but large downloading started and afterward localhost:5001 showed up in the browser.  Menu choices are there for Ultralytics YOLO and I will work with this example shortly.
Best regards,
Alan

**Comment by yuyoujiang** [comment] 2024-09-02 01:47
Hi @almarion , Thank you very much for the important information you provided; I will take note of this. By the way, may I ask what device you are using and which version of the jetpack is installed?

**Comment by almarion** [comment] 2024-09-02 03:53
Hi yuyoujiang,

reComputer Industrial J3011-with Jetson Orin Nano 8GB

mfi_recomputer-industrial-orin-nano-8g-j201-6.0-36.3.0-2024-08-08.tar.gz
Seeed version latest Aug 8, 2024
Jetpack 6
L4T version
36.3.0

So far I can run Ultralytics Yolo script and work with image and video files, but NOT Webcam
The FPS is very slow (2 FPS) and only CPU running not GPU (see jtop)
Enable TensorRT not working

Many questions:
How to enable Webcam (USB and/or Ethernet IP camera)?
How to get reasonable FPS like in youtube video?
How to get TensorRT running to get GPU working?

Seeed Reference:
Major update for Jetson Examples' Runing Ultralytics Yolo One-Click!
https://www.youtube.com/watch?v=f3yxmVBIy5w

Comment:
The "one-click" approach seems like a good attempt to allow a person to get a quick evaluation of the product.  Seeing the Seeed youtube video convinced me that at least with the hardware and software I have, I should be able to duplicate the experience seen in the video.

Best regards,
Alan

**Comment by yuyoujiang** [comment] 2024-09-03 02:46
Hi @almarion I have discovered that this container currently does not support Jetpack 6. If you use a system with Jetpack 5, the GPU on the Jetson can be enabled successfully.

This container is developed based on the `ultralytics/ultralytics:latest-jetson` container, which seems unable to use the GPU properly in Jetpack 6. I noticed that [ultralytics](https://hub.docker.com/r/ultralytics/ultralytics/tags?page=&page_size=&ordering=&name=) has recently updated their container, and we just need to inherit the latest Jetpack 6 version from ultralytics, but we haven't had the time to update it yet. 
```bash
FROM ultralytics/ultralytics:latest-jetson
WORKDIR /usr/src/ultralytics/ultralytics-yolo
COPY . /usr/src/ultralytics
RUN pip install flask
CMD [ "python3","app.py" ]
```
By default, the code enables /dev/video0 as the camera input, supporting only USB and CSI cameras. If additional functionality is required, a new container needs to be compiled.

This is a very profound observation. We are confident and motivated to get this done, and we also hope to receive more help from developers.

**Comment by almarion** [comment] 2024-09-04 03:22
Hi yuyoujiang,
Praise the Lord!
Thanks to your guidance "reComputer run ultralytics-yolo" now works as expected.
Had to go back to Jetpack 5 and the necessary change to flash using Ubuntu 20.04 PC.
Image, video and USB webcam with TensorRT enabling 40+ FPS.
Probably should get more familiar with Docker.
Would really appreciate if you give some insight into enabling usage of a POE IP camera on LAN but especially on the second Ethernet port (PSE) on reComputer Industrial J3011.
Finally get an opportunity to investigate the applications that this hardware was meant to enable.
Best regards,
Alan

**Comment by almarion** [comment] 2024-09-09 22:39
Hi yuyoujiang,
I had to go back to JP6 to work with some applications, but even with this version, I suspect there are some issues.

mfi_recomputer-industrial-orin-nano-8g-j201-6.0-36.3.0-2024-08-08.tar.gz
Seeed version latest Aug 8, 2024
Jetpack 6

Has there been any update since Aug 8 ?
When can we realistically expect one ?

Thanks,
Alan

**Comment by yuyoujiang** [comment] 2024-09-11 02:04
Hi @almarion , You have downloaded the latest BSP package. 
I will close this issue. If you have any other questions, please open a new issue.

**Closed as completed** 2024-09-11 02:04 UTC
